### ISSUE TITLE
Validate `setup.py` contents.

### ISSUE THREAD

**Issue by NMZ0429** [NMZ0429/BiWAKO#15]
# Issue

`setup.py` lacks some dependent modules.

## Target

Update `setup.py` to latest version.

##  Resources

Any?

## TODO

- [ ] Check dependency clause
- [ ] Check author info and license.
- [ ] Test with blank environment
