### ISSUE TITLE
Add FastAPI Integration

### ISSUE THREAD

**Issue by NMZ0429** [NMZ0429/BiWAKO#23]
# Issue

Add FastAPI pre-defined code in api module.

## Target

Sample minimum implementation of how to use this repository with FastAPI for web application.

##  Resources

Will be added.

## TODO

- [ ] Write draft api and test it with post and get
- [ ] Test it with Streamlit frontend
- [ ] Test for all models in this repo
