### ISSUE TITLE
New Mode: NanoDet

### ISSUE THREAD

**Issue by NMZ0429** [NMZ0429/BiWAKO#25]
# Issue

Add lightweight object detector NanoDet

## Target

Implement NanoDet onnx module

##  Resources

[official repo](https://github.com/RangiLyu/nanodet)

## TODO

- [ ] Export model
- [ ] Upload it to release
- [ ] Write with base_interface
- [ ] Test live demo
