### ISSUE TITLE
Add video inference wrapper

### ISSUE THREAD

**Issue by NMZ0429** [NMZ0429/BiWAKO#7]
# Issue

Add some higher level API for video

## Target

With this, user can

1. pass mp4 video
2. Assign models
3. Obtain result rendered on the input video

##  Resources

Any?

## TODO

- [ ] Implement from video to images loader
- [ ] Write wrapper which takes model as an argument
- [ ] Write stacked prediction on the single video
- [ ] Export it
