### ISSUE TITLE
Add some sample output images/video

### ISSUE THREAD

**Issue by NMZ0429** [NMZ0429/BiWAKO#8]
# Issue

Add sample output/video for demo purpose

What?

Probably one image per model and some videos for selected models

##  Resources

Any?

## TODO

- [ ] Think of good examples
- [ ] Save it on `demo` folder
- [ ] Add link to them on docs site
